version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6-browsers
    steps:
      - checkout
      - ruby/install-deps
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.6.6-browsers
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: ""
      RAILS_ENV: test
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    steps:
      - checkout
      - ruby/install-deps
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
